name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the `main` branch

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Set Git config for GitHub Pages deployment
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install dependencies
        run: |
          yarn install

      - name: Build the project
        run: |
          yarn build

      - name: Set up Git authentication for GitHub Pages deployment
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Deploy to GitHub Pages
        run: |
          yarn deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
